let arr1 = [3, 7, 34, 90, 12];
let arr2 = [true, "green", "where", 12, 56];
console.log(arr1[arr1.length - 1]); 
console.log(arr2[arr2.length - 1]); 
let myPets = ["Cow", "Bird", "Snake", "Dog"];
let petsStr = myPets.join(", ");
console.log(petsStr);
let arr3 = [-5, 9, 5, 3, 2, -3, 6, 8, 4, 1];
arr3.sort((a, b) => a - b);
console.log(arr3); 
let arr = ["boy", "man", "girl", "school", "girl", "woman"];
let uniqueArray = [...new Set(arr)];
let duplicatesArray = arr.filter((item, index) => arr.indexOf(item) !== index);
console.log(uniqueArray); 
console.log(duplicatesArray); 
let arr5 = ["the", "way", "x", 4];
let searchWord = "food";
let result = arr5.includes(searchWord) ? searchWord : "the search word was not found";
console.log(result); 
let word = "renniw";
let sortedWord = word.split("").sort().join("");
console.log(sortedWord);
let fruits = Array(10).fill("Fruit");
fruits[4] = "Tomato";
console.log(fruits);